import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="h-[100dvh] box-border">
        <header className="h-[60px] bg-orange-500">여기는 헤더</header>
        <section className="h-[calc(100dvh-60px)]">{children}</section>
        {/* <footer className="h-[220px]">여기는 푸터</footer> */}
      </body>
    </html>
  );
}
